name: C Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc make
      
    - name: Compile and run tests on Linux
      run: |
        # Компилируем основную библиотеку
        gcc -c src/set_iterator.c -Iinclude -o src/set_iterator.o
        
        # Компилируем тесты
        gcc -c test/test.c -Iinclude -o test/test.o
        
        # Линкуем и запускаем тесты
        gcc test/test.o src/set_iterator.o -o test_executable
        ./test_executable
        
        # Проверяем код возврата
        if [ $? -eq 0 ]; then
          echo "All tests passed on Linux!"
        else
          echo "Tests failed on Linux!"
          exit 1
        fi

  windows-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install MinGW for Windows
      run: choco install mingw -y
      
    - name: Set up PATH for MinGW
      run: |
        $mingwPath = "C:\MinGW\bin"
        $env:PATH = "$mingwPath;$env:PATH"
        echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
      
    - name: Compile and run tests on Windows
      run: |
        # Компилируем основную библиотеку
        gcc -c src/set_iterator.c -Iinclude -o src/set_iterator.o
        
        # Компилируем тесты
        gcc -c test/test.c -Iinclude -o test/test.o
        
        # Линкуем и запускаем тесты
        gcc test/test.o src/set_iterator.o -o test_executable.exe
        
        # Запускаем тесты
        .\test_executable.exe
        
        if ($LASTEXITCODE -eq 0) {
          Write-Host "All tests passed on Windows!"
        } else {
          Write-Host "Tests failed on Windows!"
          exit 1
        }