name: Simple C Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install build tools
      run: sudo apt-get install -y build-essential gcc
      
    - name: Compile main program
      run: gcc -o main src/main.c -Iinclude
      
    - name: Compile tests
      run: gcc -o test_runner tests/test_main.c -Iinclude
      
    - name: Run tests
      run: ./test_runner
      
    - name: Check test exit code
      run: |
        ./test_runner
        if [ $? -eq 0 ]; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi